/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A command parsed from a justfile */
export interface JustCommand {
  /** Command name (e.g., "test", "build") */
  name: string
  /** Description from comment above the command */
  description?: string
  /** The recipe/shell commands */
  recipe: string
}
/** Service status */
export const enum ServiceStatus {
  Running = 'Running',
  Stopped = 'Stopped',
  Starting = 'Starting',
  Error = 'Error'
}
/** Service type - determines what features are available */
export const enum ServiceType {
  /** Database services (PostgreSQL, MySQL, MongoDB) - can create databases */
  Database = 'Database',
  /** Message brokers (RabbitMQ) - can create vhosts */
  MessageBroker = 'MessageBroker',
  /** Cache services (Redis) - no extra features */
  Cache = 'Cache',
  /** Other services (NATS, etc.) - no extra features */
  Other = 'Other'
}
/** Docker service */
export interface DockerService {
  id: string
  name: string
  image: string
  status: string
  port?: number
  serviceType: string
}
/** Check if Docker is available */
export declare function dockerIsAvailable(): Promise<boolean>
/** List all Docker services */
export declare function dockerListServices(): Promise<Array<DockerService>>
/** Start a Docker service */
export declare function dockerStartService(serviceId: string): Promise<void>
/** Stop a Docker service */
export declare function dockerStopService(serviceId: string): Promise<void>
/** Restart a Docker service */
export declare function dockerRestartService(serviceId: string): Promise<void>
/** Get container logs */
export declare function dockerGetLogs(serviceId: string, tail?: number | undefined | null): Promise<Array<string>>
/** Remove a Docker service */
export declare function dockerRemoveService(serviceId: string): Promise<void>
/**
 * Create a database in a database container
 * Returns the connection string for the new database
 */
export declare function dockerCreateDatabase(serviceId: string, dbName: string): Promise<string>
/**
 * Create a vhost in RabbitMQ
 * Returns the connection string for the new vhost
 */
export declare function dockerCreateVhost(serviceId: string, vhostName: string): Promise<string>
/** Parse a justfile and return all commands */
export declare function justfileParse(path: string): Array<JustCommand>
/** Run a just command in a directory */
export declare function justfileRun(command: string, cwd: string): string
/**
 * Initialize the application state and register a listener for state updates.
 *
 * The callback will be invoked with the JSON-serialized state whenever it changes.
 * This should be called once during app startup.
 */
export declare function stateInit(callback: (err: Error | null, state: string) => void): void
/** Get the current state as JSON. */
export declare function stateGet(): Promise<string>
/**
 * Dispatch an action to update the state.
 *
 * The action should be a JSON object with the format:
 * `{ "type": "ActionName", "payload": { ... } }`
 *
 * After the action is processed, the state listener will be notified.
 */
export declare function stateDispatch(actionJson: string): Promise<void>
