/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A command parsed from a justfile */
export interface JustCommand {
  /** Command name (e.g., "test", "build") */
  name: string
  /** Description from comment above the command */
  description?: string
  /** The recipe/shell commands */
  recipe: string
}
/** Service status */
export const enum ServiceStatus {
  Running = 'Running',
  Stopped = 'Stopped',
  Starting = 'Starting',
  Error = 'Error'
}
/** Service type - determines what features are available */
export const enum ServiceType {
  /** Database services (PostgreSQL, MySQL, MongoDB) - can create databases */
  Database = 'Database',
  /** Message brokers (RabbitMQ) - can create vhosts */
  MessageBroker = 'MessageBroker',
  /** Cache services (Redis) - no extra features */
  Cache = 'Cache',
  /** Other services (NATS, etc.) - no extra features */
  Other = 'Other'
}
/** Docker service */
export interface DockerService {
  id: string
  name: string
  image: string
  status: string
  port?: number
  serviceType: string
  /** Project group (e.g., "tech-platform", "rstn", "pg-bench") */
  projectGroup?: string
  /** Whether this container is managed by rstn (rstn-* prefix) */
  isRstnManaged: boolean
}
/** Port conflict information for napi export */
export interface PortConflictInfo {
  /** The port that was requested */
  requestedPort: number
  /** Docker container ID of the conflicting container */
  containerId: string
  /** Container name (e.g., "tech-platform-postgres") */
  containerName: string
  /** Container image */
  containerImage: string
  /** Whether this container is managed by rstn (rstn-* prefix) */
  isRstnManaged: boolean
  /** Suggested alternative port */
  suggestedPort: number
}
/** Check if Docker is available */
export declare function dockerIsAvailable(): Promise<boolean>
/** List all Docker services */
export declare function dockerListServices(): Promise<Array<DockerService>>
/** Start a Docker service */
export declare function dockerStartService(serviceId: string): Promise<void>
/** Stop a Docker service */
export declare function dockerStopService(serviceId: string): Promise<void>
/** Restart a Docker service */
export declare function dockerRestartService(serviceId: string): Promise<void>
/** Get container logs */
export declare function dockerGetLogs(serviceId: string, tail?: number | undefined | null): Promise<Array<string>>
/** Remove a Docker service */
export declare function dockerRemoveService(serviceId: string): Promise<void>
/**
 * Create a database in a database container
 * Returns the connection string for the new database
 */
export declare function dockerCreateDatabase(serviceId: string, dbName: string): Promise<string>
/**
 * Create a vhost in RabbitMQ
 * Returns the connection string for the new vhost
 */
export declare function dockerCreateVhost(serviceId: string, vhostName: string): Promise<string>
/** Start a Docker service with a specific port override */
export declare function dockerStartServiceWithPort(serviceId: string, port: number): Promise<void>
/** Stop any Docker container by ID or name */
export declare function dockerStopContainer(containerId: string): Promise<void>
/** Check for port conflict before starting a service */
export declare function dockerCheckPortConflict(serviceId: string): Promise<PortConflictInfo | null>
/** Parse a justfile and return all commands */
export declare function justfileParse(path: string): Array<JustCommand>
/** Run a just command in a directory */
export declare function justfileRun(command: string, cwd: string): string
/**
 * Read a file from allowed scopes (project root or ~/.rstn/).
 *
 * # Arguments
 * * `path` - Absolute path to the file
 * * `project_root` - Project root directory (security scope)
 *
 * # Security
 * Only files within project_root or ~/.rstn/ can be read.
 *
 * # Errors
 * - FILE_NOT_FOUND: File does not exist
 * - PERMISSION_DENIED: OS permission denied
 * - SECURITY_VIOLATION: Path outside allowed scope
 * - FILE_TOO_LARGE: File exceeds 10MB limit
 * - NOT_UTF8: File is not valid UTF-8 text
 */
export declare function fileRead(path: string, projectRoot: string): string
/**
 * Read a binary file with security validation.
 *
 * Returns raw bytes as a Buffer. For security, files must be within:
 * - project_root or its subdirectories
 * - ~/.rstn/ or its subdirectories
 *
 * Only files within project_root or ~/.rstn/ can be read.
 *
 * # Errors
 * - FILE_NOT_FOUND: File does not exist
 * - PERMISSION_DENIED: OS permission denied
 * - SECURITY_VIOLATION: Path outside allowed scope
 * - FILE_TOO_LARGE: File exceeds 10MB limit
 */
export declare function fileReadBinary(path: string, projectRoot: string): Buffer
/** File entry for napi export (tree view) */
export interface NapiFileEntry {
  name: string
  path: string
  kind: string
  size: number
  permissions: string
  updatedAt: string
  commentCount: number
  gitStatus?: string
}
/**
 * List files in a directory without mutating state.
 * Used for tree view expansion.
 */
export declare function explorerListDirectory(path: string, projectRoot: string): Array<NapiFileEntry>
/** Branch info for napi export */
export interface NapiBranchInfo {
  name: string
  hasWorktree: boolean
  isCurrent: boolean
}
/** List all branches in a repository */
export declare function worktreeListBranches(repoPath: string): Array<NapiBranchInfo>
/** List env files matching patterns in a directory */
export declare function envListFiles(dir: string, patterns: Array<string>): Array<string>
/** Get default env patterns */
export declare function envDefaultPatterns(): Array<string>
/** Fetch available tools from MCP server */
export declare function fetchMcpTools(): Promise<string>
/** AI Context for napi export */
export interface NapiAiContext {
  /** Open files with content */
  openFiles: Array<NapiFileContext>
  /** Last terminal output */
  terminalLastOutput?: string
  /** Git status summary */
  gitStatus: string
  /** Active errors */
  activeErrors: Array<string>
  /** Directory tree */
  directoryTree?: string
  /** Git diff */
  gitDiff?: string
}
/** File context for napi export */
export interface NapiFileContext {
  /** File path */
  path: string
  /** File content (may be truncated) */
  content: string
  /** Cursor line if available */
  cursorLine?: number
}
/**
 * Build AI context for a project path
 *
 * Gathers context from git, files, and other sources within a token budget.
 */
export declare function contextBuild(projectPath: string, activeFiles: Array<string>, taskOutput: string | undefined | null, dockerErrors: Array<string>, tokenBudget?: number | undefined | null): NapiAiContext
/** Build AI context and format as a system prompt string */
export declare function contextBuildSystemPrompt(projectPath: string, activeFiles: Array<string>, taskOutput: string | undefined | null, dockerErrors: Array<string>, tokenBudget?: number | undefined | null): string
/**
 * Initialize the application state and register a listener for state updates.
 *
 * The callback will be invoked with the JSON-serialized state whenever it changes.
 * This should be called once during app startup.
 */
export declare function stateInit(callback: (err: Error | null, state: string) => void): void
/** Get the current state as JSON. */
export declare function stateGet(): Promise<string>
/**
 * Dispatch an action to update the state.
 *
 * The action should be a JSON object with the format:
 * `{ "type": "ActionName", "payload": { ... } }`
 *
 * After the action is processed, the state listener will be notified.
 */
export declare function stateDispatch(actionJson: string): Promise<void>
