/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Service status */
export const enum ServiceStatus {
  Running = 'Running',
  Stopped = 'Stopped',
  Starting = 'Starting',
  Error = 'Error'
}
/** Docker service */
export interface DockerService {
  id: string
  name: string
  image: string
  status: string
  port?: number
}
/** Check if Docker is available */
export declare function dockerIsAvailable(): Promise<boolean>
/** List all Docker services */
export declare function dockerListServices(): Promise<Array<DockerService>>
/** Start a Docker service */
export declare function dockerStartService(serviceId: string): Promise<void>
/** Stop a Docker service */
export declare function dockerStopService(serviceId: string): Promise<void>
/** Restart a Docker service */
export declare function dockerRestartService(serviceId: string): Promise<void>
/** Get container logs */
export declare function dockerGetLogs(serviceId: string, tail?: number | undefined | null): Promise<Array<string>>
/** Remove a Docker service */
export declare function dockerRemoveService(serviceId: string): Promise<void>
